### ISSUE TITLE
<em> marker inside of blockquote is not visible

### ISSUE THREAD

**Issue by dakrone** [vividvilla/ezhil#12]
When I write something in markdown like the following:

```
Text text text

> this is a *quote*
```

Using the `*` to make the word "quote" emphasized, the resulting HTML includes the `<em>` tag around the word, however, nothing in the CSS shows the word any different than the other quoted text.

**Comment by vividvilla** [comment]
Thanks for reporting, I have pushed an update here (https://github.com/vividvilla/ezhil/commit/1ab28caf4fc8664ad779b84a0f3e42741c974ee0) to highlight `em` tags inside `blockquote`.

**Comment by dakrone** [comment]
Thanks!
