### ISSUE TITLE
Improved custom theming

### ISSUE THREAD

**Issue by cgiax** [vividvilla/ezhil#22]
First of all, great job with the theme. I really like the addition of dark mode, and that is why I am adding this issue. 

It would be really great if the theme supported advanced custom theming with the ability to specify:

- Primary color used for the anchors
- Background color
- Primary text color for titles and text
- Secondary text colors used for the dates and support text.

The values could be specified in the config file for easy customization

**Comment by vividvilla** [comment]
I think this should be done using `customCSS` and `customJS` config by user, if we start implementing theming in config then its going to become cumbersome to maintain it.
