### ISSUE TITLE
Looks different when hosted on Github page

### ISSUE THREAD

**Issue by josephbak** [vividvilla/ezhil#23]
The site looks different when hosted locally and when hosted on the Github page.
The dark mode doesn't work on the Github page and everything is ordered weirdly. 
Does anyone know how to fix this?

**Comment by ghost** [comment]
I have the same problem as you. Did you solve it? @JosephBak
The site layouts in disorder when I use 'hugo -t ezhil' and 'hugo -D' to publish my site then push to Github pages.
How to fix it? @vividvilla, please...

**Comment by ghost** [comment]
> I have the same problem as you. Did you solve it? @JosephBak
> The site layouts in disorder when I use 'hugo -t ezhil' and 'hugo -D' to publish my site then push to Github pages.
> How to fix it? @vividvilla, please...

It's working now!
I found the mistake in my config.toml: 
the correct conf is "customCSS = "/css/main.css"" and "customJS = ["/js/feather.min.js", "https://code.jquery.com/jquery-3.4.1.js"]", 

it's solved.
