### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by jserpapinto** [vividvilla/ezhil#28]
Hey, 

Great job with the theme. Thanks.

GA is not working properly for what it looks like to me.
I've checked that currently they use a different tag than the one you are setting.

I haven't found how you do that magic to inject GA code, otherwise I would try to make a PR.

**New code:**
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXX-XX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXX-XX);
</script>
```

**Old code:**
```
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-XXXX-XX', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```
---

I would suggest keeping the `doNotTrack` condition, but update to the more recent code.

Thanks

**Comment by vividvilla** [comment]
Actually its an internal template built into Hugo - https://gohugo.io/templates/internal/
Either we have to create a issue in Hugo repo or ditch internal template and use our own.

**Comment by narner** [comment]
Having the same issue trying to set up Google Analytics right now with my site using ezhil - what would you recommend?

**Comment by bill3tt** [comment]
Bumped into this problem too. There's an upstream Hugo issue [here](https://github.com/gohugoio/hugo/issues/9987). The workaround was to use the analytics code recommended by Google and load it via an external JS script - [example](https://github.com/bill3tt/bill3tt.github.io/blob/main/config.toml#L23).
