### ISSUE TITLE
Shortcode highlight CSS

### ISSUE THREAD

**Issue by colachg** [vividvilla/ezhil#33]
Hi, Vivek R. I like this theme and thanks for what you have done. Yesterday I found something looks not good. 

Below is the shortcode highlight:

![Screenshot from 2019-11-08 17-38-59](https://user-images.githubusercontent.com/6825116/68466553-98f3ae00-024f-11ea-9cd1-23cdf7de87d6.png)

**Comment by colachg** [comment]
```
.highlight pre {
    margin-bottom: 0;
    margin-top: 0;
    padding: 20px;
    /* background-color: transparent !important; */
}
```
I comment background-color out and it looks a bit comfortable.

<img width="753" alt="Screen Shot 2019-11-09 at 19 02 00" src="https://user-images.githubusercontent.com/6825116/68527605-aed2a300-0323-11ea-8ee0-5dc604fceb21.png">

I think the code line number and copy button are good as what gitbook did.

**Comment by vividvilla** [comment]
Have pushed some fix for `pre` tag background. Also try using `solarized-dark` as `pygmentsstyle`, you can check demo to see how it looks. 

```
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
```

**Comment by AntixK** [comment]
I have the updated version of your theme and the issue still persists - especially C++ code blocks are utterly unreadable. I tried playing around with different pygmentsstyles but the background colour doesn't actually change. 
Any suggestions how to fix this issue?
