### ISSUE TITLE
Fix table spacing

### ISSUE THREAD

**Issue by ajeetdsouza** [vividvilla/ezhil#35]
Ezhil's styling for tables at the moment leaves no padding around the content, resulting in rather unreadable tables. Perhaps we could add some padding and/or a light border around the cells?

For example, this:

```markdown
| filesize |    time | memory  |
| --------:| -------:| ------ :|
|   100 MB |  0.64 s | 2060 KB |
|   100 MB |  0.62 s | 1816 KB |
|   500 MB |  3.13 s | 2084 KB |
|   500 MB |  1.98 s | 1852 KB |
```

Looks like this:

![image](https://user-images.githubusercontent.com/1777663/69123570-b7676e00-0ac7-11ea-8ab5-d7bedc87b328.png)

Even the [demo page](https://themes.gohugo.io//theme/ezhil/post/markdown-syntax/) has poor  spacing between blocks in the header.

**Comment by vividvilla** [comment]
Thanks for reporting, added a default style for table. Here is the demo - https://ezhil-hugo.netlify.com/posts/post-5/#Tables
