### ISSUE TITLE
MathJax Support

### ISSUE THREAD

**Issue by mivinci** [vividvilla/ezhil#38]
How do I add MathJax support to ezhil?

**Comment by vividvilla** [comment]
You can use [`customJS` config param](https://github.com/vividvilla/ezhil#configuration) to add MathJax to your header. You can have something like this in your config file 

```
customJS = ["https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js"]
```

**Comment by mehrdad3301** [comment]
this didn't work for me. For anyone reading this, I solved it following https://stackoverflow.com/questions/64050359/how-to-use-markdown-syntax-to-write-math-in-hugo
