### ISSUE TITLE
Post title in landing page is small

### ISSUE THREAD

**Issue by ChenXiyu** [vividvilla/ezhil#44]
Hey, Thanks for your great work on this, It's awesome.
And I noticed that the newest code just resolved the "issue" which the Markdown syntaxis didn't render on the landing page (Post desciptions).

But after these fixes, I found that the post title looks too small especially the "description" under the title was rendered with Markdown syntax.

something looks like this:
![image](https://user-images.githubusercontent.com/7472567/74639816-86bbd100-51a9-11ea-965d-8de759941855.png)

(Forget about the Chinese contents)
Do you have any suggestions to solve this?

**Comment by vividvilla** [comment]
I didn't get your question properly but is this about summary length? If so you can [set the length in config using `summaryLength`](https://github.com/vividvilla/ezhil/blob/master/exampleSite/config.toml#L16)

**Comment by ChenXiyu** [comment]
Thank you for your reply, and sorry for the misleading, actually it's not about the `summaryLength`.
I do want to show some information on the landing page, So I just add `<!--more-->` tag in my post after the content which I willing to display at the landing page.

What really bothering me is when I display some content which includes markdown, It will be rendered, and some times the rendered content is larger than the post title. Just like the screenshot shows above.

**Comment by vividvilla** [comment]
One thing you can do is to set a `description` tag in your content which will override the automatic summary.

**Comment by ChenXiyu** [comment]
OK, Thank you very much.
