### ISSUE TITLE
POSTS page does render

### ISSUE THREAD

**Issue by ghost** [vividvilla/ezhil#5]
I have built and hosted a blog site using Ezhil Theme. Everything works except for the /posts directory. Even if I build an exact replica of a site using Ezhil with no modifications, it does not work correctly.

```
$ hugo env
```
> Hugo Static Site Generator v0.55.6 linux/amd64 BuildDate: 2019-05-18T11:36:07Z
> GOOS="linux"
> GOARCH="amd64"
> GOVERSION="go1.12.5"

```
$ hugo server --verbose -D
```
> INFO 2019/06/14 17:30:11 No translation bundle found for default language "en"
> INFO 2019/06/14 17:30:11 Translation func for language en not found, use default.
> INFO 2019/06/14 17:30:11 i18n not initialized; if you need string translations, check that you have a > bundle in /i18n that matches the site language or the default language.
> INFO 2019/06/14 17:30:11 Using config file: 
> Building sites … INFO 2019/06/14 17:30:11 syncing static files to /
> INFO 2019/06/14 17:30:11 found taxonomies: map[string]string{"tag":"tags"}
>
>                    | EN  
> +------------------+----+
> Pages            |  4  
> Paginator pages  |  0  
> Non-page files   |  0  
> Static files     |  4  
> Processed images |  0  
> Aliases          |  0  
> Sitemaps         |  1  
> Cleaned          |  0  
>
> Total in 12 ms
> Watching for changes in /home/qih/site-workspace/ezhil-vanilla/{content,data,layouts,static,themes}
> Watching for config changes in /home/qih/site-workspace/ezhil-vanilla/config.toml
> Environment: "development"
> Serving pages from memory
> Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
> Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
> Press Ctrl+C to stop

If you require further information, please advise.

**Comment by vividvilla** [comment]
The key is adding your content markdown files in `content/posts` directory and if its standalone page then add it outside. You can check example site structure here - https://github.com/vividvilla/ezhil/tree/master/exampleSite

For example lets say you want directory page `/cats` then create `content/cats` and add your cat related content inside that.

**Comment by ghost** [comment]
Hi,

Thanks for the reply. I have worked it out how to use your THEME now:

$ cd site/content
$ mkdir -p maps
$ mkdir -p posts
$ cd site/

# To make a post in the maps/, you need to:
/../site $ hugo new maps/index.md
/../site $ hugo new maps/this-is-a-map.md

# To make a post in the posts/, you need to:
/../site $ hugo new posts/this-is-the-first-post.md

Now I can see a new post in the 'All Posts' page titled, 'This is the first
post',
and a post on the 'Maps' page titled 'This is a map'.

I will write up a complete HOWTO to use your THEME for newbs (Like me)
haha. When I get some free time, I might have a go at enhancing it and
submit a PR.

You can close that ISSUE now.

Enjoy your weekend 8-)

**Comment by vividvilla** [comment]
Looking forward to your PR 👍  thanks a lot
