### ISSUE TITLE
Footnotes don't work as intended

### ISSUE THREAD

**Issue by ajossorioarana** [vividvilla/ezhil#54]
Hi! First of all, nice theme.

Footnotes show properly, but the links don't work. A live example can be seen in [this test post](https://vanhelmont.github.io/blog/communication/)

I couldn't find a footnote example in the live demo of the theme, either.

Thanks in advance

EDIT: Hugo version: 0.72

**Comment by vividvilla** [comment]
There was a fix suggested here (#58) but it turned out to be a non-issue in Hugo v0.75.1. Try upgrading your Hugo version and check if you could reproduce it still. Feel free to reopen this issue in case it's still broken for you.
