### ISSUE TITLE
Link to "All Articles" is hardcoded

### ISSUE THREAD

**Issue by OverkillGuy** [vividvilla/ezhil#6]
Changing the content folder's layout to something other than default doesn't adjust the index.html template, causing broken link for hugo sites diverging from default. It's not a big deal, but it definitely surprised me. Extra docs or a new parameter can fix this easily.

### Reproduction
Change the content folder to `/post` or other "non-standard" folder
My (local) site has the following:

```toml
[[menu.main]]
name = "All posts"
url = "/post"
weight = 2
```
### Expected behaviour
Homepage link "All Posts" points to the new folder `/post`

### Actual behaviour
Broken link pointing to `/posts/` when clicking the "All Posts" link of the home page.

### Root cause
The index.html template has `/posts/` hardcoded.

https://github.com/vividvilla/ezhil/blob/0e06bb53c586e19dec2aa0dc8ade0579a70526a3/layouts/index.html#L36

### Suggested fix
Extra documentation? Adding a parameter?

**Comment by vividvilla** [comment]
Thanks for reporting, this should ideally come from config file, will fix it in next update.

**Comment by vividvilla** [comment]
Introduced pagination to recent posts list and we use `params.mainSections` to filter contents to display on home page instead of `params.excludeTypes`. You can check the [commit here](https://github.com/vividvilla/ezhil/commit/bb28e76551834a70f1889fb7601b49e5abd7e328)
