### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by bitwombat** [vividvilla/ezhil#7]
Does ezhil support images in posts? I tried Hugo's built-in shortcode `{{ <figure> }}`, but ezhil's CSS for `img` blows any images out to 100% of the container width.

**Comment by vividvilla** [comment]
I have tried figure shortcode on Ezhil sample site and it seems to render fine. Here is the shortcode I used to test.

```
{{< figure src="https://images.unsplash.com/photo-1560032779-0a8809186efd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" title="Dave Herring" >}}
``` 

and this is how it rendered 

![image](https://user-images.githubusercontent.com/715529/62624741-5f09c780-b941-11e9-93b8-7c728e0edcb6.png)

**Comment by bitwombat** [comment]
Sorry, I should have been more specific.

There's this CSS in `main.css`.

```
audio, canvas, img, video {
    width: 100%;
    vertical-align: middle;
}
```

This has the effect of taking my tidy little thumbnail image (256x256) and blowing it out to a fuzzy 680x680, at my current browser window width. Like so:

![image](https://user-images.githubusercontent.com/3937658/62661104-5eaa1480-b9b3-11e9-8ce3-72241bb81c73.png)

What I was expecting was for the image to keep its dimensions, like so:

![image](https://user-images.githubusercontent.com/3937658/62661152-93b66700-b9b3-11e9-9cc0-6a68c32dad9f.png)

The CSS even overrides something like this:

`{{< figure src="/images/development-haskell.png" title="Lambda logo" height="100px" width="100px">}}`

**Comment by vividvilla** [comment]
Also added a shortcode demo page which shows how different sized images are rendered - https://ezhil-hugo.netlify.com/posts/post-6/

Thanks for notifying the issue.
