### ISSUE TITLE
Custom social parameter

### ISSUE THREAD

**Issue by YazidKurdi** [vividvilla/ezhil#8]
Hello,

I am using your theme for a while now, however I can not seem to find a way to add a custom social parameter, I would appreciate it if you help me

**Comment by vividvilla** [comment]
Thanks for using Ezhil, you can configure social links by adding `params.social` config block to `config.toml`. Check the [sample config file here](https://github.com/vividvilla/ezhil/blob/master/exampleSite/config.toml#L42).

For example if you are adding Linked profile then config will look like

```
[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com"
```

You can search for icon names in [Feather icons site](https://feathericons.com/).
