### ISSUE TITLE
CSS and Javascript appears to be hardcoded to top level path

### ISSUE THREAD

**Issue by dakrone** [vividvilla/ezhil#9]
I'm trying to set up a blog under a sub-folder, and when I generate the layout with Hugo, I see this HTML:

https://github.com/vividvilla/ezhil/blob/74e9ee7758cb3e8a8698c43a043cb0f87b4cbe6b/layouts/partials/header.html#L21-L22

Which leads to a site that looks like:

![Screenshot_2019-08-09_11-09-11](https://user-images.githubusercontent.com/19060/62796308-28919100-ba96-11e9-80f2-5c9d7e7e3ba1.png)

If I go into dev tools and change it to `css/normalize.css` and `css/main.css` (removing the leading `/`) the site correctly displays the theme.

I think this is also a problem for

https://github.com/vividvilla/ezhil/blob/74e9ee7758cb3e8a8698c43a043cb0f87b4cbe6b/layouts/partials/header.html#L27

and

https://github.com/vividvilla/ezhil/blob/74e9ee7758cb3e8a8698c43a043cb0f87b4cbe6b/layouts/partials/header.html#L29

**Comment by dakrone** [comment]
It looks like (just looking at a different hugo theme), these need to be changed to:

```
<link rel="stylesheet" href="{{ .Site.BaseURL }}css/normalize.css">
<link rel="stylesheet" href="{{ .Site.BaseURL }}css/main.css">
```

etc (for all the hardcoded links)

**Comment by dakrone** [comment]
@vividvilla I could probably submit a PR for this if you're interested?

**Comment by vividvilla** [comment]
I would appreciate that :)

**Comment by vividvilla** [comment]
Thanks for notifying the issue, its fixed https://github.com/vividvilla/ezhil/commit/411c986a01939b053d386441872528e790eb72f7

**Comment by tfalamu** [comment]
> It looks like (just looking at a different hugo theme), these need to be changed to:
> 
> ```
> <link rel="stylesheet" href="{{ .Site.BaseURL }}css/normalize.css">
> <link rel="stylesheet" href="{{ .Site.BaseURL }}css/main.css">
> ```
> 
> etc (for all the hardcoded links)

I understand this was closed but just noting here that the BaseURL has to be appended with a '/'. Site wasn't loading any css for me, that was why.
